
server:
  port: 10012
  servlet:
    context-path: /qcloud



cos:
  appid: 1259716940
  bucket: test
  region: ap-shanghai
  secretId: AKIDhQt62jSMGm8E4dvqMYewxiKL0UfAqPDm
  secretKey: UjrjV1GEzBE8vT1KNAakfK3XmKcgbIVT